### ISSUE TITLE
Not safe for real world use

### ISSUE THREAD

**Issue by gpetersson** [palucki/QStegano#1]
Because the program writes the hidden data in a way that can be easily detected (either by the program itself or by external tools), this method of steganography is not suitable for real world use and I think it is dangerous not to warn the user about this. 

Steganography is concerned with concealing the fact that a secret message is being sent, but when you have a header and CRC method that can be detected, your cover is blown completely.

**Comment by palucki** [comment]
Hello, thanks for your report and further input.
Please keep in mind, that this project serves educational purposes in a first place.
Yes, I agree header presence is not suitable for any production/operational applications.
I created #2 to fix it there, hence closing this one.
